[versions]
assertk = "0.27.0"
changelog = "2.2.0"
detekt = "1.23.0"
githooks = "0.0.2"
junitParams = "5.10.0"
kotlin = "1.9.0"
kotlinCompileTesting = "1.5.0"
kotlinxSerializationCbor = "1.6.0"
ksp = "1.9.0-1.0.13"
minecraft = "1.20.1"
minotaur = "2+"
quiltKotlinLibraries = "2.1.2+kt.1.9.0+flk.1.10.8"
quiltLicenser = "1.+"
quiltLoader = "0.21.0-beta.4"
quiltLoom = "1.3.+"
quiltMappings = "1.20.1+build.23"
quiltMappingsClassifier = "intermediary-v2"
quiltStandardLibraries = "6.1.2+1.20.1"
quiltedFabricApi = "7.2.2+0.88.1-1.20.1"

[libraries]
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitParams" }
kotlin-compileTestingKsp = { group = "com.github.tschuchortdev", name = "kotlin-compile-testing-ksp", version.ref = "kotlinCompileTesting" }
kotlinx-serializationCbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "kotlinxSerializationCbor" }
ksp-symbolProcessingApi = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
quilt-kotlinLibraries = { group = "org.quiltmc.quilt-kotlin-libraries", name = "quilt-kotlin-libraries", version.ref = "quiltKotlinLibraries" }
quilt-loader = { group = "org.quiltmc", name = "quilt-loader", version.ref = "quiltLoader" }
quilt-mappings = { group = "org.quiltmc", name = "quilt-mappings", version.ref = "quiltMappings" }
quilt-standardLibraries = { group = "org.quiltmc", name = "qsl", version.ref = "quiltStandardLibraries" }
quilt-qslCoreTesting = { group = "org.quiltmc.qsl.core", name = "testing", version.ref = "quiltStandardLibraries" }
quilted-fabricDataGenerationApiV1 = { group = "org.quiltmc.quilted-fabric-api", name = "fabric-data-generation-api-v1", version.ref = "quiltedFabricApi" }

# for buildLogic
changelog-gradlePlugin = { group = "org.jetbrains.intellij.plugins", name = "gradle-changelog-plugin", version.ref = "changelog" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
minotaur-gradlePlugin = { group = "com.modrinth.minotaur", name = "com.modrinth.minotaur.gradle.plugin", version.ref = "minotaur" }
quilt-licenserGradlePlugin = { group = "org.quiltmc.gradle.licenser", name = "org.quiltmc.gradle.licenser.gradle.plugin", version.ref = "quiltLicenser" }
quilt-loomGradlePlugin = { group = "org.quiltmc", name = "loom", version.ref = "quiltLoom" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
githooks = { id = "com.github.jakemarsden.git-hooks", version.ref = "githooks" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
quilt-licenser = { id = "org.quiltmc.gradle.licenser", version.ref = "quiltLicenser" }
quilt-loom = { id = "org.quiltmc.loom", version.ref = "quiltLoom" }
